server:
  port: 8081

spring:
  application:
    name: security-client

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  #secret: QNRqNJyrJmbHWg1SJt1RsXBfZyC/YfQ0j38bfMZ1D54
  secret: ${JWT_SECRET}
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka