server:
  port: 8081

spring:
  application:
    name: security-client

  datasource:
    #url: jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:5432/postgres?sslmode=require
    #url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.girhjbzrxqwvjjrsanbn
    password: Dwomor@22#Smoke@22#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: QNRqNJyrJmbHWg1SJt1RsXBfZyC/YfQ0j38bfMZ1D54
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka